openapi: 3.0.0
servers:
  - url: https://api-testnet.bybit.com
    description: Testnet server
info:
  description: |
    Collection of v5 Restul API
  version: 3.0.0
  title: Bybit Open API v5 explorer
tags:
  - name: account
    description: Account endpoints
    x-displayName: Account
x-tagGroups:
  - name: private
    tags:
      - account
paths:
  /v5/account/wallet-balance:
    get:
      tags:
        - account
      summary: Get Wallet Balance
      description: Get wallet balance. Please read [API-DOC](../../../v5/account/wallet-balance#) first.
      operationId: wallet
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: accountType
          in: query
          description: Account type
          required: true
          schema:
            type: string
            enum:
              - UNIFIED
        - name: coin
          in: query
          description: Coin name
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/account/upgrade-to-uta:
    post:
      tags:
        - account
      summary: Upgrade Unified Account
      description: Upgrade to UTA. Please read [API-DOC](../../../v5/account/upgrade-unified-account#) first.
      operationId: upgrade-uta
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
  /v5/account/borrow-history:
    get:
      tags:
        - account
      summary: Get Borrow History
      description: Get borrow history. Please read [API-DOC](../../../v5/account/borrow-history#) first.
      operationId: borrow-history
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: currency
          in: query
          description: e.g., USDC, USDT, BTC, ETH
          required: false
          schema:
            type: string
        - name: startTime
          in: query
          description: The start timestamp (ms)
          required: false
          schema:
            type: integer
        - name: endTime
          in: query
          description: The end timestamp (ms)
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Limit per page. 1-50
          required: false
          schema:
            type: integer
            default: 20
        - name: cursor
          in: query
          description: Cusor, used to pagnition
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/account/collateral-info:
    get:
      tags:
        - account
      summary: Collateral Info
      description: Get collateral info. Please read [API-DOC](../../../v5/account/collateral-info#) first.
      operationId: collateral-info
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: currency
          in: query
          description: Collateral asset
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/account/coin-greeks:
    get:
      tags:
        - account
      summary: Coin Greeks
      description: Get coin greek info. Please read [API-DOC](../../../v5/account/coin-greeks#) first.
      operationId: coin-greeks
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: baseCoin
          in: query
          description: Base coin
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/account/info:
    get:
      tags:
        - account
      summary: Account Info
      description: Get account info. Please read [API-DOC](../../../v5/account/account-info#) first.
      operationId: account-info
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/account/transaction-log:
    get:
      tags:
        - account
      summary: Transaction Log
      description: Get transaction log. Please read [API-DOC](../../../v5/account/transaction-log#) first.
      operationId: transaction-log
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: accountType
          in: query
          description: Support `UNIFIED` for now
          required: false
          schema:
            type: string
            enum:
              - UNIFIED
        - name: category
          in: query
          description: Product category
          required: false
          schema:
            type: string
            enum:
              - spot
              - linear
              - option
        - name: currency
          in: query
          description: Currency
          required: false
          schema:
            type: string
        - name: baseCoin
          in: query
          description: Base coin
          required: false
          schema:
            type: string
        - name: type
          in: query
          description: Transaction log type
          required: false
          schema:
            type: string
            enum:
              - TRANSFER_IN
              - TRANSFER_OUT
              - TRADE
              - SETTLEMENT
              - DELIVERY
              - LIQUIDATION
              - BONUS
              - FEE_REFUND
              - INTEREST
              - CURRENCY_BUY
              - CURRENCY_SELL
        - name: startTime
          in: query
          description: The start timestamp (ms)
          required: false
          schema:
            type: integer
        - name: endTime
          in: query
          description: The end timestamp (ms)
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Limit size for each page. 1-50
          required: false
          schema:
            type: integer
            default: 20
        - name: cursor
          in: query
          description: Cursor, used to pagination
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/account/set-margin-mode:
    post:
      tags:
        - account
      summary: Set Margin Mode
      description: Set margin mode. Please read [API-DOC](../../../v5/account/set-margin-mode#) first.
      operationId: set-margin-mode
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                setMarginMode:
                  type: string
                  description: Margin mode
                  enum:
                    - REGULAR_MARGIN
                    - PORTFOLIO_MARGIN
                  example: PORTFOLIO_MARGIN
              required:
                - setMarginMode