openapi: 3.0.0
servers:
  - url: https://api-testnet.bybit.com
    description: Testnet server
info:
  description: |
    Collection of v5 Restul API
  version: 3.0.0
  title: Bybit Open API v5 explorer
tags:
  - name: asset
    description: Asset endpoints
    x-displayName: Asset
x-tagGroups:
  - name: private
    tags:
      - asset
paths:
  /v5/asset/transfer/query-asset-info:
    get:
      tags:
        - asset
      summary: Get Wallet Balance
      description: Get wallet balance. Please read [API-DOC](../../../v5/asset/asset-info#) first.
      operationId: asset-info
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: accountType
          in: query
          description: Account type
          required: true
          schema:
            type: string
            enum:
              - UNIFIED
        - name: coin
          in: query
          description: Coin name
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/asset/transfer/query-account-coin-balance:
    get:
      tags:
        - asset
      summary: Coin Balance Of Specific Account Type
      description: Get coin balance of specific account type. Please read [API-DOC](../../../v5/account/account-coin-balance#) first.
      operationId: account-coin-balance
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: memberId
          in: query
          description: If query sub user balance, please input sub uid
          required: false
          schema:
            type: integer
        - name: accountType
          in: query
          description: Account type
          required: false
          schema:
            type: string
            enum:
              - SPOT
              - CONTRACT
              - UNIFIED
              - OPTION
              - INVESTMENT
        - name: coin
          in: query
          description: Coin name
          required: false
          schema:
            type: string
        - name: withBonus
          in: query
          description: Query bonus or not
          required: false
          schema:
            type: integer
            enum:
              - 0
              - 1
            default: 0
      responses:
        "200":
          description: successful operation
  /v5/asset/transfer/query-transfer-coin-list:
    get:
      tags:
        - asset
      summary: Get Transferable Coin
      description: Get transferable coins. Please read [API-DOC](../../../v5/account/transferable-coin#) first.
      operationId: transferable-coin
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: fromAccountType
          in: query
          description: From account type
          required: false
          schema:
            type: string
            enum:
              - UNIFIED
              - CONTRACT
              - SPOT
              - OPTION
              - INVESTMENT
        - name: toAccountType
          in: query
          description: To account type
          required: false
          schema:
            type: string
            enum:
              - UNIFIED
              - CONTRACT
              - SPOT
              - OPTION
              - INVESTMENT
      responses:
        "200":
          description: successful operation
  /v5/asset/transfer/inter-transfer:
    post:
      tags:
        - asset
      summary: Create Internal Transfer
      description: Create internal transfer. Please read [API-DOC](../../../v5/account/create-inter-transfer#) first.
      operationId: create-inter-transfer
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                transferId:
                  type: string
                  description: UUID
                  example: 42c0cab0-6bca-c242-bc76-4e6df6cbab16
                coin:
                  type: string
                  description: Coin
                  example: USDT
                amount:
                  type: string
                  description: Amount
                  example: "10"
                fromAccountType:
                  type: string
                  description: From account type
                  enum:
                    - UNIFIED
                    - CONTRACT
                    - SPOT
                    - OPTION
                    - INVESTMENT
                  example: UNIFIED
                toAccountType:
                  type: string
                  description: To account type
                  enum:
                    - UNIFIED
                    - CONTRACT
                    - SPOT
                    - OPTION
                    - INVESTMENT
                  example: CONTRACT
              required:
                - transferId
                - coin
                - amount
                - fromAccountType
                - toAccountType
  /v5/asset/transfer/query-inter-transfer-list:
    get:
      tags:
        - asset
      summary: Get Internal Transfer Records
      description: Get internal transfer records. Please read [API-DOC](../../../v5/account/inter-transfer-list#) first.
      operationId: inter-transfer-list
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: transferId
          in: query
          description: Transfer id.
          required: false
          schema:
            type: string
        - name: coin
          in: query
          description: Coin name
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: Status
          required: false
          schema:
            type: string
            enum:
              - SUCCESS
              - PENDING
              - FAILED
        - name: startTime
          in: query
          description: The start timestamp (ms)
          required: false
          schema:
            type: integer
        - name: endTime
          in: query
          description: The end timestamp (ms)
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Limit size. 1-50
          required: false
          schema:
            type: integer
            default: 20
        - name: cursor
          in: query
          description: Cursor, used to pagination
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/asset/transfer/query-sub-member-list:
    get:
      tags:
        - asset
      summary: Get Sub UID
      description: Get sub uid. Please read [API-DOC](../../../v5/account/sub-uid-list#) first.
      operationId: sub-uid-list
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/asset/transfer/save-transfer-sub-member:
    post:
      tags:
        - asset
      summary: Enable Sub UID For Universal Transfer
      description: Enable sub uid for universal transfer. Please read [API-DOC](../../../v5/account/enable-unitransfer-subuid#) first.
      operationId: enable-unitransfer-subuid
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                subMemberIds:
                  type: array
                  description: array of sub UIDs
                  items:
                    type: string
                    example: "1234,3213,4321"
              required:
                - subMemberIds