openapi: 5.0.0
servers:
  - url: https://api-testnet.bybit.com
    description: Testnet server
info:
  description: |
    Collection of v5 Restul API
  version: 5.0.0
  title: Bybit Open API v5 explorer
tags:
  - name: market
    description: Market endpoints
    x-displayName: Market
x-tagGroups:
  - name: public
    tags:
      - market
paths:
  /v5/market/kline:
    get:
      tags:
        - market
      summary: Get Kline
      description: Get kline data
      operationId: kline
      parameters:
        - name: category
          in: query
          description: Products category
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - linear
                - inverse
        - name: symbol
          in: query
          description: Symbol name
          required: true
          schema:
            type: string
        - name: interval
          in: query
          description: kline interval
          required: true
          schema:
            type: array
            items:
              type: string
              enum:
                - 1
                - 3
                - 5
                - 15
                - 30
                - 60
                - 120
                - 240
                - 360
                - 720
                - D
                - M
                - W
        - name: start
          in: query
          description: start timestamp (ms). e.g., 1669852800000 (1 DEC 2022 UTC 0:00)
          required: true
          schema:
            type: integer
        - name: end
          in: query
          description: end timestamp (ms). e.g., 1671062400000 (15 DEC 2022 UTC 0:00)
          required: true
          schema:
            type: integer
        - name: limit
          in: query
          description: Maximum 200
          required: false
          schema:
            type: integer
            default: 200
      responses:
        "200":
          description: successful operation