openapi: 3.0.0
servers:
  - url: https://api-testnet.bybit.com
    description: Testnet server
info:
  description: |
    Collection of derivatives Restul API
  version: 3.0.0
  title: Bybit derivatives explorer
tags:
  - name: market
    description: Market endpoints of derivatives
    x-displayName: Market Data Endpoints
x-tagGroups:
  - name: public
    tags:
      - market
paths:
  /derivatives/v3/public/order-book/L2:
    get:
      tags:
        - market
      summary: Get orderbook
      description: Get order book data
      operationId: orderbook
      parameters:
        - name: category
          in: query
          description: Products category
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - future
                - option
              default: future
        - name: symbol
          in: query
          description: Symbol name
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Maximum 500
          required: false
          schema:
            type: int
            default: 25
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/orderbookResp"

  /derivatives/v3/public/kline:
    get:
      tags:
        - market
      summary: Get kline
      description: Get kline data
      operationId: kline
      parameters:
        - name: category
          in: query
          description: Products category
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - future
        - name: symbol
          in: query
          description: Symbol name
          required: true
          schema:
            type: string
        - name: interval
          in: query
          description: kline interval
          required: true
          schema:
            type: array
            items:
              type: string
              enum:
                - 1
                - 3
                - 5
                - 15
                - 30
                - 60
                - 120
                - 240
                - 360
                - 720
                - D
                - M
                - W
        - name: start
          in: query
          description: start timestamp (ms)
          required: true
          schema:
            type: integer
        - name: end
          in: query
          description: end timestamp (ms)
          required: true
          schema:
            type: integer
        - name: limit
          in: query
          description: Maximum 200
          required: false
          schema:
            type: integer
            default: 200
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/klineResp"

components:
  schemas:
    orderbookResp:
      type: object
      properties:
        retCode:
          type: integer
        retMsg:
          type: string
        result:
          type: object
          properties:
            s:
              type: string
            b:
              type: array
              items:
                type: array
                example: ["16972","2.46"]
            a:
              type: array
              items:
                type: array
                example: ["16972.5","8.818"]
            ts:
              type: integer
              format: timestamp
              example: 1668740049061
            u:
              type: integer
              format: sequence
              example: 1592092
        retExtInfo:
          type: object
        time:
          type: integer
          format: timestamp
          example: 1668740049062

    klineResp:
      type: object
      properties:
        retCode:
          type: integer
        retMsg:
          type: string
        result:
          type: object
          properties:
            symbol:
              type: string
              example: ETHUSDT
            category:
              type: string
              example: future
            list:
              type: array
              items:
                type: array
                example: ["1668441660000","16722.5","16722.5","16700","16700.5","3.307","55233.6405"]
        retExtInfo:
          type: object
        time:
          type: integer
          format: timestamp
          example: 1668740049062