openapi: 3.0.0
servers:
  - url: https://api-testnet.bybit.com
    description: Testnet server
info:
  description: |
    Collection of Spot-trade rest api.
  version: 3.0.0
  title: Bybit spot-trade explorer
tags:
  - name: institution
    description: All Institution Loan REST API
    x-displayName: OTC
paths:
  /spot/v3/public/margin-product-infos:
    get:
      tags:
        - institution
      summary: Get Margin Product Info
      description: Get Margin Product Info
      operationId: margin-product-info
      parameters:
        - name: productId
          in: query
          description: Product Id. If not passed, then return all products info
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation

  /spot/v3/public/margin-ensure-tokens:
    get:
      tags:
        - institution
      summary: Get Margin Coin Info
      description: Get Margin Coin Info
      operationId: margin-coin-info
      parameters:
        - name: productId
          in: query
          description: ProductId. If not passed, then return all product margin coin. For spot, it returns coin that convertRation greater than 0.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation

  /spot/v3/private/margin-loan-infos:
    get:
      tags:
        - institution
      summary: Get Loan Info
      description: Get Loan Info
      operationId: loan-info
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: orderId
          in: query
          description: Loan order id. If not passed, then return all orders, sort by loanTime in descend
          required: false
          schema:
            type: string
        - name: startTime
          in: query
          description: Start time, unit in millisecond
          required: false
          schema:
            type: integer
        - name: endTime
          in: query
          description: End time, unit in millisecond
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Default value is 10, max 100
          required: false
          schema:
            type: string
            default: 10
      responses:
        "200":
          description: successful operation

  /spot/v3/private/margin-repaid-infos:
    get:
      tags:
        - institution
      summary: Get Repay Info
      description: Get Repay Info
      operationId: repay-info
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: startTime
          in: query
          description: Start time, unit in millisecond
          required: false
          schema:
            type: integer
        - name: endTime
          in: query
          description: End time, unit in millisecond
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Default value is 10, max 100
          required: false
          schema:
            type: string
            default: 10
      responses:
        "200":
          description: successful operation

  /spot/v3/private/margin-ltv:
    get:
      tags:
        - institution
      summary: Get LTV
      description: Get LTV
      operationId: ltv
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string