openapi: 3.0.0
servers:
  - url: https://api-testnet.bybit.com
    description: Testnet server
info:
  description: |
    Collection of Spot Restul API
  version: 3.0.0
  title: Bybit spot explorer
tags:
  - name: market
    description: Market endpoints of spot
    x-displayName: Market data
x-tagGroups:
  - name: public
    tags:
      - market
paths:
  /spot/v3/public/symbols:
    get:
      tags:
        - market
      summary: Instrument Info
      description: Get the spec of spot symbols
      operationId: instrument-info
      parameters:
        - name: symbol
          in: query
          description: Symbol name
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation

  /spot/v3/public/quote/depth:
    get:
      tags:
        - market
      summary: Order Book
      description: Get Order Book
      operationId: order-book
      parameters:
        - name: symbol
          in: query
          description: Name of the trading pair
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Default value is 100. Max value is 200
          required: false
          schema:
            type: integer
            default: 100
      responses:
        "200":
          description: successful operation

  /spot/v3/public/quote/depth/merged:
    get:
      tags:
        - market
      summary: Merged Order Book
      description: Get Merged Order Book
      operationId: merged-order-book
      parameters:
        - name: symbol
          in: query
          description: Name of the trading pair
          required: true
          schema:
            type: string
        - name: scale
          in: query
          description: Precision of the merged orderbook, 1 means 1 digit
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Default value is 100. Max value is 200
          required: false
          schema:
            type: integer
            default: 100
      responses:
        "200":
          description: successful operation

  /spot/v3/public/quote/trades:
    get:
      tags:
        - market
      summary: Public Trading Records
      description: Get Public Trading Records
      operationId: public-trading-records
      parameters:
        - name: symbol
          in: query
          description: Name of the trading pair
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Default value is 60, max 60
          required: false
          schema:
            type: integer
            default: 60
      responses:
        "200":
          description: successful operation

  /spot/v3/public/quote/kline:
    get:
      tags:
        - market
      summary: Query Kline
      description: Get Kline
      operationId: query-kline
      parameters:
        - name: symbol
          in: query
          description: Name of the trading pair
          required: true
          schema:
            type: string
        - name: interval
          in: query
          description: kline interval
          required: true
          schema:
            type: array
            items:
              type: string
              enum:
                - 1m
                - 3m
                - 5m
                - 15m
                - 30m
                - 1h
                - 2h
                - 4h
                - 6h
                - 12h
                - 1d
                - 1w
                - 1m
        - name: limit
          in: query
          description: Default value is 1000, max 1000
          required: false
          schema:
            type: integer
            default: 1000
        - name: startTime
          in: query
          description: Start time, unit in millisecond
          required: false
          schema:
            type: integer
        - name: endTime
          in: query
          description: End time, unit in millisecond
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: successful operation

  /spot/v3/public/quote/ticker/24hr:
    get:
      tags:
        - market
      summary: Lastest Information for Symbol
      description: Get Lastest Information for Symbol
      operationId: lastest-information-for-symbol
      parameters:
        - name: symbol
          in: query
          description: Name of the trading pair
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation

  /spot/v3/public/quote/ticker/price:
    get:
      tags:
        - market
      summary: Name of the trading pair
      description: Get Last Traded Price
      operationId: last-traded-price
      parameters:
        - name: symbol
          in: query
          description: Name of the trading pair
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation

  /spot/v3/public/quote/ticker/bookTicker:
    get:
      tags:
        - market
      summary: Best Bid/Ask Price
      description: Get Best Bid/Ask Price
      operationId: best-bidask-price
      parameters:
        - name: symbol
          in: query
          description: Name of the trading pair
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation