openapi: 3.0.0
servers:
  - url: https://api-testnet.bybit.com
    description: Testnet server
info:
  description: |
    Collection of Spot-trade rest api.
  version: 3.0.0
  title: Bybit spot-trade explorer
tags:
  - name: spotTrade
    description: All spot trade REST API
    x-displayName: Trade
paths:
  /spot/v3/private/order:
    post:
      tags:
        - spotTrade
      summary: Place Order
      description: Place a order
      operationId: place-order
      parameters:
        - name: apiKey
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: If not input, the default one will be used
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                  description: Symbol name
                  example: BTCUSDT
                orderQty:
                  type: string
                  description: Market Buy order, it is amount to pay.
                  example: "0.1"
                side:
                  type: string
                  description: Side
                  enum:
                    - Buy
                    - Sell
                  example: Buy
                orderType:
                  type: string
                  description: Order type
                  enum:
                    - MARKET
                    - LIMIT
                    - LIMITMAKER
                  example: LIMIT
                timeInForce:
                  type: string
                  description: Time in force
                  enum:
                    - GTC
                    - FOK
                    - IOC
                  example: GTC
                orderPrice:
                  type: string
                  description: Order price
                  example: "10000"
                orderLinkId:
                  type: string
                  description: User customised order id
                orderCategory:
                  type: integer
                  description: Order category. 0=normal order, 1=TP/SL order
                  enum:
                    - 0
                    - 1
                  default: 0
                triggerPrice:
                  type: string
                  description: Tp/Sl order trigger price
                  example:
              required:
                - symbol
                - orderQty
                - side
                - orderType